### ISSUE TITLE
 False positive: "whitespace before ':' (E203)"

### ISSUE THREAD

**Issue by tkzt** [TCLResearchEurope/ctw-pre-commit-hooks#3]
Following [pep8 convention](https://peps.python.org/pep-0008/#whitespace-in-expressions-and-statements), black will make sure both sides of colon in slicing operation have a whitespace, which will then trigger the E203 error of flake8.

And it is [recommended](https://github.com/psf/black/issues/280#issuecomment-393124792) to ignore `E203`.

Any expression formatted by black like this:

```
topics[page * size : page * size + size]
```

can then trigger `E203`.

**Comment by micpod** [comment]
It is fixed now, thanks for raising it.
